config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :links
  root 'links#new'
  get ':shorted_url' => 'links#go'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  validates :original_url, :shorted_url, presence: true
  validates :shorted_url, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def new
  end

  def create
    @link = Link.new(link_params)
    @link.shorted_url = SecureRandom.hex(4)
    if @link.save
      redirect_to link_path(@link)
    else
      render 'new'
    end
  end

  def show
    @link =  Link.find(params[:id])
  end

  def go
    @link = Link.find_by(shorted_url: params[:shorted_url])
    redirect_to @link.original_url, :status => 302
  end

  private
  def link_params
    params.require(:link).permit(:original_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/new.html.erb
<%= form_for :link , url: links_path do |f| %>
  <div class="form-group">
    <%= f.label :Enter_the_URL %><br>
    <%= f.text_field :original_url %>
  
 
  
    <%= f.submit %>
  </div>
<% end %>

app/views/links/show.html.erb
<p>
  <strong>Original URL:</strong>
  <%= @link.original_url %>
</p>
 
<p>
  <strong>Shorted URL:</strong>
  <%= @link.shorted_url %>
</p>